### ISSUE TITLE
How to install without Metacello-Work?

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/vivide#124]
I cannot install Metacello as laid out in the metacello-work repository from the readme. Thus, I have no class named Metacello in my image and cannot follow the installation instructions for Vivide.

If I remember correctly, there is a set of more cumbersome commands to load packages without the new Metacello API. Do you have those lying around somewhere and can post the alternative installation instructions here or in the Wiki? Or is it not possible to install Vivide without the bleeding edge Metacello?

**Comment by marceltaeumel** [comment]
You can checkout Vivide, Widgets, Signals, and Animations manually and user FileTree to access them in the image. You also have to load the other dependencies (OCompletion etc.) as defined in the respective baselines manually.

What's the problem with loading Metacello?

**Comment by j4yk** [comment]
Either your telling me 'it should work, try it again' last week did help or it was me retrying it in a shorter directory path. Anyway, I got Metacello and Vivide installed now. Thank you. ;-)
