### ISSUE TITLE
Cannot click proceed in debugger

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/vivide#127]
When I hover the proceed button in the debugger, the cursor changes to resizing the window. Thus, the button does not react to red clicks.

Vivide-mt.679

**Comment by marceltaeumel** [comment]
This is a bug in Suqeak 5.0. I can cherry-pick the fix from trunk once the commit process in the 5.0 branch is working again. (http://forum.world.st/Squeak-5-0-Strange-Commit-Behavior-td4858951.html)

See: http://forum.world.st/The-Trunk-Morphic-mt-999-mcz-td4845514.html

**Comment by marceltaeumel** [comment]
I did cherrypick that fix for 5.0. Please make an update of Squeak 5.0.
