### ISSUE TITLE
How to create a category and categorize a method?

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/vivide#128]
I have a method opened in an Artifacts window for a class.

What is the easiest way to create a new method category in that class and place the method into it?

**Comment by j4yk** [comment]
I would tag this with 'beginner' myself, but I am not allowed to do so. :-)

**Comment by marceltaeumel** [comment]
This this help?

![Working with Categories](https://github.com/hpi-swa/vivide/blob/master/howto/howto-categories.gif)

**Comment by marceltaeumel** [comment]
The class definition editor provides access to its categories. There is also a script (Protocols) that lists all ViProtocol objects that represent the class' categories:

![protocols](https://cloud.githubusercontent.com/assets/5765308/10910661/ef907704-8240-11e5-9ad9-e5ccf8a1e9f2.png)
