### ISSUE TITLE
Collections inspected from the standard debugger are wrapped in an additional array

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/vivide#129]
While debugging a method and inspecting the result of an expression which returns a collection, the tool opened by Vivide shows the result collection wrapped in another array. This could mislead the developer to believe that the result of the inspected expression were indeed a nested collection. I would like to see in the opened tool window only the inner collection selected in the screenshot.

![image](https://cloud.githubusercontent.com/assets/151175/11097074/83f941ac-889d-11e5-8a89-fe629beba1d0.png)

**Comment by marceltaeumel** [comment]
dc6c8b364d54bf113141a5f79c6485459760d9a7
