### ISSUE TITLE
Script serialization: separate lines and standardize ordering

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/vivide#132]
Serializing profile archives to put scripts under version control and to share them works right now.
But it is difficult to read the git diffs on GitHub (when you do not want to fetch, open Squeak, refresh there etc. when your team mate pushed something late in the evening) because

1. the code of a step is all in one line and 
2. the properties seem to jump around from commit to commit because the insertion order of properties into the created Dictionary does not seem to be stable.

I would like to suggest putting each `#add:` on a separate line and emitting them lexicographically ordered by the association key. It might be desirable to put id, label, creator, ... essentially the standard ones first as an exception to this rule.

As indicated, the goal is a more readable diff and more stable code files overall.

**Comment by marceltaeumel** [comment]
You can provide a custom serialization format by implementing `Dictionary >> #storeCompactOn:`, which Vivide added to provide a compact store-string for strike fonts and block closures. For other objects, it just works like `#storeOn:'.

![storecompacton-1](https://cloud.githubusercontent.com/assets/5765308/11501308/6b3c9f56-9833-11e5-894a-3406b29ed158.png)

**Comment by marceltaeumel** [comment]
991a0e9abf6770987d89376815f1778b2c76cee0

Now, it looks like this and hence supports better diffing in GitHub:

```Smalltalk
(Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'1258312c-a457-db40-aa96-499fda6b7623').
(#label -> nil).
(#next -> #'e68d82d7-0f82-5e4f-990d-0b292c42da7f').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4410)}))})
```

**Comment by marceltaeumel** [comment]
Note that the keys within a dictionary are sorted lexicographically.

**Comment by j4yk** [comment]
It should be much better on GitHub now, but the Monticello diff is "pretty"-printed and thus does not benefit from the update:

![image](https://cloud.githubusercontent.com/assets/151175/12646449/77271dbc-c5d0-11e5-9322-20f3a20ac5e6.png)
(hint: only the label has changed)

I suppose if you would have stuck to #add:-ing the individual asscociations, that would not be the case because the pretty-printer puts cascaded sends on multiple lines.

**Comment by marceltaeumel** [comment]
You can disable pretty diffs in Squeak's preferences.
