### ISSUE TITLE
script editor text is cropped on small screens

### ISSUE THREAD

**Issue by abstraktor** [hpi-swa/vivide#135]
# Setup
- OSX (Macbook Pro with Retina display: 2560 x 1600)
- in vivide mt.693
- Squeak 5.3
- Screen resolution OS-scaled to 1440x900

# Steps to reproduce

open a script in vivide and fold it. The fold details (e.g. `inputKind`) are cropped

![image](https://cloud.githubusercontent.com/assets/569215/11691126/f094174e-9e99-11e5-9183-48780686659f.png)

**Comment by marceltaeumel** [comment]
Here is another example of this behavior with more context to illustrate that text is wrapped correctly while the fold details only get cropped:

![small-screen](https://cloud.githubusercontent.com/assets/5765308/11743772/6b6404cc-a00a-11e5-853b-599c4304b4c3.png)

**Comment by marceltaeumel** [comment]
Do you mean the wrt. the height of the font or the width of the string?

**Comment by marceltaeumel** [comment]
Is this better now?

![script-editor-label-cut](https://cloud.githubusercontent.com/assets/5765308/12414557/87094750-be96-11e5-9958-725cf66bb2a1.png)
