### ISSUE TITLE
ViLocalScriptArchive doesNotUnderstand: #id during update

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/vivide#145]
When I use the code provided in the FAQ to update Vivide, it trips over the ViLocalScriptArchive. In `ViQuerySerializer>>mergeProfile` the profile of an archive is queried, but the local archive does not have one. In contrast to a profile's serialized archive, it does not even implement the `id` method. Later in mergeProfile, the archive is asked for a `label` which is not implemented for the local archive as well.

I provisioned my image with Vivide in late October or early November 2015, do I fight some outdated state again?

Yesterday, I did a first update of Vivide before I reported the closing windows issue. Today, the problem appeared again for the next update, so I assume the issue pertains to the current code base.

My workaround is to add `theArchive respondsTo: #id ifFalse: [^nil]` (or likewise, so that it makes sense in the context) and the same with `#label` in `ViScriptArchive class>>profile` and `ViQuerySerializer>>mergeProfile` (two occurrences).

This has the side effect of creating a new unnamed profile on every attempt to update.

Here the stack trace:
```
MessageNotUnderstood: ViLocalScriptArchive class>>id
ViLocalScriptArchive class(Object)>>doesNotUnderstand: #id
[] in ViLocalScriptArchive class(ViScriptArchive class)>>profile
[] in OrderedCollection(Collection)>>detect:ifNone:
OrderedCollection>>do:
OrderedCollection(Collection)>>detect:ifNone:
ViLocalScriptArchive class(ViScriptArchive class)>>profile
ViQuerySerializer>>mergeProfile
ViQuerySerializer>>merge
ViLocalScriptArchive class(ViScriptArchive class)>>merge
[] in ViScriptArchive class>>mergeAll
[] in [] in Array(Collection)>>do:displayingProgress:every:
Array(SequenceableCollection)>>do:
[] in Array(Collection)>>do:displayingProgress:every:
[] in [] in MorphicUIManager>>displayProgress:at:from:to:during:
BlockClosure>>on:do:
[] in MorphicUIManager>>displayProgress:at:from:to:during:
BlockClosure>>ensure:
MorphicUIManager>>displayProgress:at:from:to:during:
ProgressInitiationException>>defaultResumeValue
ProgressInitiationException(Exception)>>resume
```

**Comment by marceltaeumel** [comment]
6b07402903e33c9e13a3af2f1016692cb4641009

Thank you for this elaborate error report.
