### ISSUE TITLE
Give a id to a tool

### ISSUE THREAD

**Issue by hubx** [hpi-swa/vivide#23]
I wanted to give input from my tool somewhere:

#stackOverflow openScriptWith: {aString}.

so I had to do:

self first id: #MyScriptName
self register....

**Comment by hubx** [comment]
What was the complete code for registering a Tool again?

**Comment by marceltaeumel** [comment]
A tool is a script (or a meta script) with a bunch of input objects.

Each script has an organization where all its related script should be registered, too.

There is one special organization that stores a set of default scripts:

```Smalltalk
ViQueryOrganizer default.
```

By default, script id lookup will happen in that object:

```Smalltalk
#senders openScriptWith: #(with: with:with:).
```

If you want to make use of this convenient programming interface, adopt a script's organization to be the default one:

```Smalltalk
| myScript |
myScript := [ActiveWorld submorphs] asScript.
myScript id: #somethingToBeRemembered.
myScript adoptOrganization: ViQueryOrganizer default.
```
Then you can do something like this:

```Smalltalk
#somethingToBeRemembered openScript.
```

If the script has multiple parts, all of those parts will be adopted to the new organization:

```Smalltalk
| longScript |
longScript := {
   [ActiveWorld submorphs].
   [:morph | morph color].
   [:color | {
      #text -> color storeString.
      #icon -> ((Form extent: 16@16 depth: 32) fillColor: color) } ]
} asScript.
longScript adoptOrganization: ViQueryOrganizer default.
(longScript steps collect: [:s | s organization]) asSet in: [:o |
   self assert: 1 equals: o size.
   self assert: o first == ViQueryOrganizer default].
```

**Comment by marceltaeumel** [comment]
That is, you cannot register tools but just the scripts **w/o any input object**). For now. ;)

Drag-and-drop to the bookmarks area on the left, however, works with input objects and does **not** require the user to adopt to the default organization.
