### ISSUE TITLE
ButtonWidget usage is not intuitive

### ISSUE THREAD

**Issue by calmez** [hpi-swa/vivide#25]
When I want to use a button, it is not discoverable how I use it's functionality. From other widgets I know the ```#text``` property which also works here as the button title.

Example scenario:
![screen shot 2015-01-28 at 12 27 04 2](https://cloud.githubusercontent.com/assets/203611/5936902/873a64cc-a6e9-11e4-9580-3d90615f23da.png)

In ```ViButtonBarView```'s ```updateFor:in:``` method I found that there is ```#clicked``` and ```#enabled```, but somehow I struggle to get them to work.

**Comment by marceltaeumel** [comment]
```Smalltalk
[:object | {
   #text -> 'Hello, World!'.
   #clicked -> [ [Transcript cr; show: 'Hello, World!'] ] }
```

The callback is a nested block because regular blocks are just late-bound model data extractors:

```Smalltalk
[:morph | #color -> [morph color]].
```

Whenever the widget accesses `node at. #color` it gets the actual color of the morph because the block will be evaluated in background.
