### ISSUE TITLE
Saving state in a script

### ISSUE THREAD

**Issue by calmez** [hpi-swa/vivide#28]
I want to save state in a script to implement a toggle button, but I don't know where to put that information.

![screen shot 2015-01-29 at 11 34 46 2](https://cloud.githubusercontent.com/assets/203611/5956197/5a45041e-a7ab-11e4-9c9c-28884f67b1ef.png)

The buttons in the image should (de)activate each other when clicked such that a toggle button would be the outcome where only one of the two buttons is enabled.

**Comment by marceltaeumel** [comment]
It could be, that the exact mechanics of the standard system browser cannot -- and maybe should not -- be reimplemented with scripts.

Think about the role of these buttons and what you want to indicate in a data-driven sense.

Anyhow, you may try something like this:

```Smalltalk
[:class |
   | view |
   view := thisView.
  { #text -> 'Class'. #clicked -> [ [
      (view submorphThat: [:m | m theText = 'Instance']) hide.
      view select: class theMetaClass. ] ] } ].
```

**Comment by marceltaeumel** [comment]
Maybe, we need a button bar that uses `UiToolButton` instances where you could configure `#autoExclusive:` in the script. :sweat_smile:  (Just like `#enabled:` in this one.)
