### ISSUE TITLE
ViTreePlainView(ViStandardItemView)>>ensureSelection fails after update to mt.494

### ISSUE THREAD

**Issue by calmez** [hpi-swa/vivide#33]
After I was updating to the most recent version mt.494 (as of the creation of this issue) ```ViTreePlainView(ViStandardItemView)>>ensureSelection``` was failing because a view apparently does not understand ```selectFirst```.

**Comment by marceltaeumel** [comment]
https://github.com/marceltaeumel/widgets/blob/master/repository/Widgets.package/UiAbstractItemView.class/instance/selectFirst.st

Don't forget to update Vivide with all its dependencies -- Widgets in this case:

```Smalltalk
Metacello new
  baseline: 'Vivide';
  repository: 'github://hpi-swa/vivide/repository';
  get;
  load.
```

**Comment by calmez** [comment]
> On 10 Feb 2015, at 13:27, Marcel Taeumel <notifications@github.com> wrote:
> Don't forget to update Vivide with all its dependencies -- Widgets in this case:
> 
> Metacello new
>   baseline: 'Vivide';
>   repository: 'github://hpi-swa/vivide/repository';
>   get;
>   load.

This was exactly what I did. :)

**Comment by marceltaeumel** [comment]
Then it is a bug in Metacello. I will contact Dale.
