### ISSUE TITLE
Merging archives into profiles

### ISSUE THREAD

**Issue by calmez** [hpi-swa/vivide#37]
When trying to merge archives into profiles (as done in current ```postLoad```) I get the following exception:

![screen shot 2015-02-11 at 14 45 19](https://cloud.githubusercontent.com/assets/203611/6148768/74575344-b204-11e4-9e4f-bbf928890fee.png)

Problematic code is: `ViScriptArchive mergeAll.`

The problem seems to be that old script code (here `ViQueryTransformStep`) gets merged with new `ViScriptPart`s.

Do I somehow need to migrate old scripts to new ones?

**Comment by marceltaeumel** [comment]
You could try to comment-out the error. Could work.

**Comment by marceltaeumel** [comment]
What is the problematic script? `self id` would be helpful. :smile:

**Comment by calmez** [comment]
It’s the `#outline`

**Comment by marceltaeumel** [comment]
Fixed here: f6967b96ce508da00568e6ec6fa14c68d1bae9c7
