### ISSUE TITLE
Reference Steps and Profile Organizations

### ISSUE THREAD

**Issue by calmez** [hpi-swa/vivide#51]
When I write a script for a new tool it would be helpful to be able to reference steps I store in my profile's organization. These steps (in the profile I use) are probably that useful that I (or somebody else) put them there. So instead of having to copy such a step over to the organization of the new tool I am about to create it would be nice if the tool's organization could simply ask the active profile's organization if it knows a step with the ID I am referencing.

**Comment by calmez** [comment]
Otherwise if for some reason organizations should not talk to each other bootstrapping the new tool's organization on creation with the steps and definitions of the profile's organizations would also solve this problem.

**Comment by marceltaeumel** [comment]
I just added that feature. But only in the interpreter, not in the script's enumeration interface.
