### ISSUE TITLE
Honor / Support Mouse Over for Keyboard Focus

### ISSUE THREAD

**Issue by calmez** [hpi-swa/vivide#58]
Also reported in #43

**Comment by j4yk** [comment]
+1

may I add a screencast reminding of the problem:

![focusmouse-vs-vividepopups](https://cloud.githubusercontent.com/assets/151175/12598606/915f9b0a-c48b-11e5-861d-df148e728a01.gif)

**Comment by marceltaeumel** [comment]
Thanks! 8c3e1d4f798c9ecb06cca39b7bd35993a578c6a5
