### ISSUE TITLE
Serializing Bookmarks

### ISSUE THREAD

**Issue by calmez** [hpi-swa/vivide#60]
Currently serializing bookmarks from a ```ViProfile``` does not work. When doing so (e. g. by dropping the bookmark onto a ```ViObjectGate``` I get the following error:

'This Context was not included in the ImageSegment'
![screen shot 2015-05-18 at 15 51 59](https://cloud.githubusercontent.com/assets/203611/7682110/dc0c5cd4-fd75-11e4-8084-e47c6c0c5004.png)

This also happens during manual serialization via ```ReferenceStream```s.

**Comment by marceltaeumel** [comment]
Should work now: e3d3c645dde5201140db59693fb9abfb27ed8eba
