### ISSUE TITLE
Script reexecution through events

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa/vivide#63]
Scripts should be updated when the displayed artifacts change. Therefore, there has to be a way to register scripts as observers to different ChangeNotifiers. We also need a way to filter whether Notifications to the script actually affect artifacts displayed through the script.

From my perspective this is not a property of the script source but of the script in general. Thus it should be denoted with the properties of the script. Example:

````Smalltalk
[:in :out | (
	[:objects | objects collect: [:ohmGrammar | ohmGrammar rules associations]]
		value: in) do: [:result |
			(ViQueryInterpreter isCollection: result)
				ifTrue: [out addAll: result]
				ifFalse: [out add: result]]]
-> {
	#id -> #OhmGrammarRules.
	#inputKind -> OhmGrammar.
	#label -> 'Ohm Rules'.
	#priority -> 5.
	#view -> ViTreeViewExtended.

        "All get called when new objects flow into the system" 
        #changesRegistration -> [:objects | 
             SystemChangeNotifier ... register: thisScript .. selector: #artifactChange ]
        #changesFilter -> [:objects | 
               "Returns a block with the current artifacts bound. 
                The block is called for each notification." 
               [:event| objects includes: event modifiedObject] ]
        #changesUpdate -> [ 
               "Returns the new input for the script and functions basically 
               as a second way to fill the input of the script"]
        #changesUnregistration -> [:objects | 
               "Returns a block which has the current artifacts bound" 
               ["Is called before the next changesRegistration call" 
                ChangeNotifier unregister for: ...]]
}
````

**Comment by marceltaeumel** [comment]
```Smalltalk
[:in :out | "..."]
-> {
  #update -> MyUpdater.
}
```

**Comment by codeZeilen** [comment]
Notes on the discussion on the first draft:

* `#changesUpdate` is conceptually unnecessary as we can bin the model as the observer. The model is then reset when it is notified. As a result it reruns the script sequence when its children are accessed.
* Ideally, the registration and unregistration code is hidden and only visible as a configuration. 
* The filter code should be configurable, e.g. as a block which allows arbitrary code to decide whether the change is relevant for the script or not.

* These requirements might make an adapter necessary to unify the registration interfaces of the different ChangeNotifiers

I'll see if I can produce a better draft tomorrow :)

**Comment by marceltaeumel** [comment]
Scripts can be updated on model changes again: 801dc13c0df5526d716dd379d2af251041fdfa80
