### ISSUE TITLE
Multipane Widget Outgoing Objects not displayed

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa/vivide#65]
When adding a result connection from a pane to its enclosing multi pane widget the notification over the connection works perfectly fine. However, when opening the halos on the multi pane widget and opening the outgoing objects box, it always shows nil instead of the objects actually passed out.

**Comment by marceltaeumel** [comment]
Fixed here: 7422d9c44d36594a913758fde9da3b4cf5735d01
