### ISSUE TITLE
Does not understand in initializing adapter for PluggableListMorphPlus

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa/vivide#76]
The initialization code in ViPluggableListMorph>>initialize does not work, as the method dragTypeSelector: does not exist anywhere in the image.

**Comment by codeZeilen** [comment]
btw: Deleting solved the issue for me.

**Comment by codeZeilen** [comment]
This happens as the defaultView must now be set explicitely. The default view is a Morph not yet fully implemented. To change the default view use:

ViProfile active defaultView: ViTreeViewExtended

**Comment by marceltaeumel** [comment]
Fixed here: 7baf9ace9a274b19de1f6a9657261a6809a8ee60
