### ISSUE TITLE
Model-independent notifier that is not polling but event-based

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/vivide#83]
Let's say we have three scripts `A`, `B` and `C` (see below). `A` displays a list.
If `C` changes this very list, `A` needs to be updated. This could be archived using a `ViTimedNotifier`, but sometimes that seems overkill or it is even impractical. When `A` is updated, `B` and `C` are also going to be updated and if `C` for example displays editable text, it's just impossible to change this text, because `C` is constantly being updated.

It'd be great if it is possible to notify a certain script on demand, like this:

```bash
[ A ] <----
  |       |
[ B ]     |
  |       | (C notifies A)
[ C ] ----|
```

**Comment by marceltaeumel** [comment]
This is a nice idea. We could add a pool of such notifiers to the active profile. Then, one script could say:

```Smalltalk
[:in :out | ...]
-> {
   ...
   #notifier -> [ViEventNotifier named: #someFancyName].
}
```

And any other script might try to call that notifier in some widget-triggered updates such as a button callback:

```Smalltalk
[:object | {
   #text -> 'Accept'.
   #clicked -> [[ (ViEventNotifier named: #someFancyName) signal ]]. } ].
```

Or when changing the model in a text view:

```Smalltalk
[:object | {
   #text -> [object asString]
      <- [:newText | object doSomething: newText.
            (ViEventNotifier named: #someFancyName) signal ]. } ].
```

**Comment by fniephaus** [comment]
`signal` -> `trigger` :smiley:

**Comment by marceltaeumel** [comment]
Have fun: 9e31f3fd83641f579c94c1fc24fd6c7e5cae2e0f :smile:

**Comment by fniephaus** [comment]
Nice!

**Comment by fniephaus** [comment]
Works like a charm!
https://github.com/matthias-springer/smalltalk-nested-classes/commit/632b01a4578b9deb9de11feedbbce14db8ac4bdd#diff-1c218ec14ee5115b61d7a04089e8bf6dR10
