### ISSUE TITLE
Squeak Inspector opening instead of Vivide Tool when opening a reference to a method

### ISSUE THREAD

**Issue by calmez** [hpi-swa/vivide#84]
On double click: Squeak Inspector
On drag and drop: Vivide Tool (Artifacts)

**Comment by marceltaeumel** [comment]
You might need to re-execute the following part of Vivide's post-load code:

```Smalltalk
(Smalltalk at: #ViToolSet ifAbsent: [])
	ifNotNil: [:ts | ToolSet default: ts].
```

To check, evaluate `ToolSet default`, which must be a `ViToolSet`.

**Comment by calmez** [comment]
> On 22 Jun 2015, at 15:04, Marcel Taeumel <notifications@github.com> wrote:
> (Smalltalk at: #ViToolSet ifAbsent: [])
>     ifNotNil: [:ts | ToolSet default: ts].

Yes. That works.

**Comment by marceltaeumel** [comment]
I added it to FAQ.
