### ISSUE TITLE
Context menus

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa/vivide#87]
Vivide is an interface build around artifacts. Therefore, when we want to implement context menus we could implement them as tools for a type of artifact. This would allow us to have these context menus wherever this type of artifact is used.

**Comment by marceltaeumel** [comment]
Here's an idea for how to specify those menus in a script:

```Smalltalk
[:morph | {
   #text -> (morph printStringLimitedTo: 30).
   #menu -> #( #('Show Halo' #addHalo) #('Browse class' #browse) ).
}].
```

Or with less magic and more explicit callbacks:

```Smalltalk
[:morph | {
   #text -> (morph printStringLimitedTo: 30).
   #menu -> { 
      { 'Show Halo'. UiSilkIcons tickIcon. [morph addHalo] }.
      { 'Browse class'. nil. [morph class browse] } }.
}].
```

Of course, this depends on how the widgets interpret the data stored in `#menu`. One possible spec could be similar to https://github.com/hpi-swa/vivide/blob/master/repository/Vivide.package/ViMethodEditor.class/instance/initializeToolbarOperations.st

**Comment by codeZeilen** [comment]
This however, would bind context menus to certain scripts. I think of a
context menu more as an artifact menu, which is a menu available for an
artifact wherever it is displayed. For example: Wherever a class is
displayed (in whatever form), I want to be able to rename the class. I know
that this adds another dimension to the UI and might be out of scope for
the scripts, but it would be quite nice :)

Marcel Taeumel <notifications@github.com> schrieb am Mi., 24. Juni 2015 um
11:41 Uhr:

**Comment by marceltaeumel** [comment]
At the moment, there are generic context menus available for most default views. These menus list possible scripts to invoke on the current selection.

![context-menu-1](https://cloud.githubusercontent.com/assets/5765308/12785915/01958cc8-ca8f-11e5-8f43-5521eb62f362.png)

Nevertheless, any view might decide to accept a property such as `#menu` in a custom format to construct menus out of it.
